package com.company;

import javax.swing.*;
import java.awt.*;
public class STable2 {
    STable2(){
        JFrame frame =new JFrame("List of Hospitals");
        frame.setSize(1200,900);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.getContentPane().setLayout(new FlowLayout());
        JTextArea t=new JTextArea(39,90);
        JScrollPane scrollableTextArea = new JScrollPane(t);
        t.setText("A\r\n\n"
                        + "• Advanced Eye Hospital and Institute\r\n"
                        + "• Asian Heart Institute\r\n"
                        + "• Aashirwad Critical Care Unit And Multispeciality Hospital\r\n"
                        + "• Aayush Eye Clinic\r\n"
                        + "• Aditi Hospital\r\n"
                        + "\n B\r\n\n"
                        + "• B.D. Petit Parsee General Hospital\r\n"
                        + "• Bhabha Hospital\r\n"
                        + "• Bhaktivedanta Hospital\r\n"
                        + "• Bombay Hospital\r\n"
                        + "• Breach Candy Hospital\r\n"
                        + "\n C\r\n\n"
                        + "• Cama Hospital\r\n"
                        + "• Currae Hospital\r\n"
                        + "• Criticare Multi Speciality Hospital & Research \r\n"
                        + "• Centre Cuddles N Cure Children Hospital \r\n"
                        + "• Contacare Eye Hospital\r\n"
                        + "\n D\r\n\n"
                        + "• Dalvi Nursing Home \r\n"
                        + "• Dhanashri Hospital \r\n"
                        + "• Dhanwantary Hospital & Iccu \r\n"
                        + "• Disha Nursing Home \r\n"
                        + "• Dr L H Hiranandani Hospital\r\n"
                        + "\n E\r\n\n"
                        + "• Eye Essential Hospital\r\n"
                        + "\n F\r\n\n"
                        + "• Family Care Hospitals\r\n"
                        + "• Fortis Hospitals Ltd Mulund\r\n"
                        + "\n G\r\n\n"
                        + "•\tGokuldas Tejpal Hospital\r\n"
                        + "• Gokul Nursing Home & Iccu"
                        + "\n H\r\n\n"
                        + "• Hinduhridaysamrat Balasaheb Thackeray Medical College and Dr. R. N. Cooper Municipal General Hospital\r\n"
                        + "• Holy Family Hospital, Mumbai\r\n"
                        + "• Holy Spirit Hospital (Mumbai)\r\n"
                        + "• Hayyat Multispeciality Hospital \r\n"
                        + "• Hcg Apex Cancer Hospital\r\n"
                        + "\n J\r\n\n"
                        + "• Jaslok Hospital\r\n"
                        + "• JJ Hospital\r\n"
                        + "\n K\r\n\n"
                        + "• Kasturba Hospital (Mumbai)\r\n"
                        + "• King Edward Memorial Hospital and Seth Gordhandas Sunderdas Medical College\r\n"
                        + "• Kokilaben Dhirubhai Ambani Hospital\r\n"
                        + "• K J Somaiya Hospital & Research Center \r\n"
                        + "• Kohinoor Hospitals Private Limited\r\n"
                        + "\n L\r\n\n"
                        + "• Lilavati Hospital and Research Centre\r\n"
                        + "• Lokmanya Tilak Municipal Medical College and General Hospital\r\n"
                        + "• Lifeline Medicare Hospital Pvt Ltd \r\n"
                        + "• Lifewave Hospital\r\n"
                        + "\n M\r\n\n"
                        + "• Masina Hospital\r\n"
                        + "• Madhu Polyclinic & Nursing Home \r\n"
                        + "• Mahavir Maternity &general Hospital \r\n"
                        + "• Manisha Universal Multispeciality Hospital\r\n"
                        + "• Modi General Hospital & Icu\r\n"
                        + "\n N\r\n\n"
                        + "• Nanavati hospital\r\n"
                        + "• Nakshatra Multispeciality Hospital Llp \r\n"
                        + "• Narendra Hospital \r\n"
                        + "• National Hospital & ICCU \r\n"
                        + "• New Life Maternity And Children Hospital\r\n"
                        + "\n O\r\n\n"
                        + "• Om Navjeevan Hospital Pvt Ltd\r\n"
                        + "• Oscar Multispeciality Hospital\r\n"
                        + "• Orbit Eye Hospital\r\n"
                        + "\n P\r\n\n"
                        + "• P.D. Hinduja National Hospital and Medical Research Centre\r\n"
                        + "• Parsi Lying-in Hospital\r\n"
                        + "• Prince Aly Khan Hospital\r\n"
                        + "• Parvatibai Chavan Charitable Trust \r\n"
                        + "• Phoenix Hospitals Pvt Ltd\r\n"
                        + ""
                        + "\n R\r\n\n"
                        + "• Rajawadi Hospital\r\n"
                        + "• Radha Krishna Hospital \r\n"
                        + "• Riddhi Vinayak Critical Care And Cardiac Centre \r\n"
                        + "• Ravi Surgical Nursing Home \r\n"
                        + "• Ruby Medical Centre\r\n"
                        + ""
                        + "\n S\r\n\n"
                        + "• Saifee Hospital\r\n"
                        + "• St George Hospital, Mumbai\r\n"
                        + "• SevenHills Hospital\r\n"
                        + "• Shushrusha Citizens' Co-operative Hospital\r\n"
                        + "• Shushrusha's Suman Ramesh Tulsiani Hospital\r\n"
                        + "• Sir H. N. Reliance Foundation Hospital\r\n"
                        + "\n T\r\n\n "
                        + "• Tata Memorial Centre\r\n"
                        + "• Thunga Healthcare Llp \r\n"
                        + "• Trident Hospital\r\n"
                        + "\n U\r\n\n"
                        + "• Umrao Hospitals\r\n"
                        + "\n V\r\n\n"
                        + "• Vardhaman Hospital & Iccu \r\n"
                        + "• Vijayalaxmi Maternity, Surgical & General Hospital \r\n"
                        + "• Vivanta Hospital\r\n"
                        + "\r\n"
                        + "\n Z\r\n\n"
                        + "• Zynova Heart Care Pvt Ltd"
                        + "\r\n"
                        + "\r\n"
                        + ""
        );
        t.setFont(new Font("Franklin Gothic Medium",Font.PLAIN,14));

        scrollableTextArea.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        frame.getContentPane().add(scrollableTextArea);

        //sc.setBounds(0, 0, 350, 300);
        frame.setVisible(true);
    }

}
